### ISSUE TITLE
procfs flag doesn't work properly

### ISSUE THREAD

**Issue by morytyann** [openwrt/procd#12]
I am using `procd_add_jail` in init script, the program need to read `/proc/${pid}`, so i set `procfs` flag to the jail, but it doesn't work properly, i can't find any folder named by pid under `/proc` which is need by the program.

I tried to use `procd_add_jail_mount /proc`, but another bug appeared, program can't read the memory usage of itself.

So is this a bug or a feature? If it's a bug, is there any workaround?

**Comment by dangowrt** [comment]
It's a feature :wink:
procd jail uses PID namespaces, which means that the process will only see itself as PID 1 and no other processes in `/proc/`.

**Comment by morytyann** [comment]
I see, and this is also why memory usage is wrong when i mount /proc by `procd_add_jail_mount /proc`, it will read the memory usage of process which pid is 1.
